const cards = [
// ===== QUOTES - LIGHT & GENTLE (1-50) =====
{type:'quote',emoji:'🌸',text:'You are the main character. The plot is thickening. Keep going.',sub:'— your story'},
{type:'quote',emoji:'✨',text:"You don't have to be productive every single day. Some days are for existing, and that's enough.",sub:'— gentle reminder'},
{type:'quote',emoji:'🦋',text:"The butterfly doesn't know how beautiful it is. But everyone else does. That's you.",sub:"— you're lovely"},
{type:'quote',emoji:'🌙',text:"Rest is not giving up. It's gathering strength for the next chapter.",sub:'— be kind to yourself'},
{type:'quote',emoji:'💫',text:"You survived 100% of your worst days. That's an undefeated record.",sub:'— unbreakable'},
{type:'quote',emoji:'🌷',text:'Let yourself be a beginner. Nobody starts as a masterpiece.',sub:'— patience'},
{type:'quote',emoji:'☁️',text:"Not everything needs to be figured out today. Some answers come with time, like flowers in spring.",sub:'— trust the timing'},
{type:'quote',emoji:'🕊️',text:"You don't owe anyone an explanation for taking care of yourself.",sub:'— boundaries are love'},
{type:'quote',emoji:'🌺',text:"Healing isn't linear. Some days you bloom, some days you rest. Both are growth.",sub:'— gentle progress'},
{type:'quote',emoji:'💐',text:"You're not behind. You're not late. You're exactly where you need to be right now.",sub:'— your own timeline'},
{type:'quote',emoji:'🌼',text:"Small steps still move you forward. Even a single breath counts as progress.",sub:'— micro wins'},
{type:'quote',emoji:'🍃',text:"You don't need to have it all figured out to move forward. Just take the next step.",sub:'— one foot ahead'},
{type:'quote',emoji:'🌱',text:"Be patient with yourself. You're growing in ways you can't even see yet.",sub:'— invisible growth'},
{type:'quote',emoji:'🪴',text:"You are a garden, not a machine. You need seasons, not just schedules.",sub:'— organic living'},
{type:'quote',emoji:'🌿',text:"Some of the best things in life happened after you almost gave up. Keep going.",sub:'— almost there'},
{type:'quote',emoji:'🌻',text:"You don't have to be sunshine every day. Even cloudy skies are part of the weather.",sub:'— permission to feel'},
{type:'quote',emoji:'🌾',text:"Progress isn't always visible. Seeds grow underground before they break the surface.",sub:'— underground magic'},
{type:'quote',emoji:'🍂',text:"Letting go isn't giving up. It's making space for what comes next.",sub:'— release'},
{type:'quote',emoji:'🌊',text:"Waves don't apologize for crashing. You don't have to apologize for feeling things deeply.",sub:'— feel everything'},
{type:'quote',emoji:'⭐',text:"You are somebody's reason to smile today. Even if you don't know it.",sub:'— ripple effect'},
{type:'quote',emoji:'🌟',text:"The fact that you're trying is the bravest thing. Most people don't even start.",sub:'— brave one'},
{type:'quote',emoji:'💛',text:"You are allowed to outgrow things that once felt like home.",sub:'— evolution'},
{type:'quote',emoji:'🌈',text:"After the rain, there's always something growing. Always.",sub:'— trust the process'},
{type:'quote',emoji:'🦋',text:"Your wings are ready. Your mind just needs to catch up.",sub:'— ready to fly'},
{type:'quote',emoji:'🌙',text:"The night is temporary. Dawn always comes. Always.",sub:'— dawn is coming'},
{type:'quote',emoji:'💫',text:"You are not too much. You are not too little. You are exactly the right amount.",sub:'— just right'},
{type:'quote',emoji:'🌸',text:"Comparison is the thief of joy. Your garden grows at its own pace.",sub:'— your pace'},
{type:'quote',emoji:'✨',text:"What if everything is working out exactly as it should? What if you just can't see it yet?",sub:'— trust'},
{type:'quote',emoji:'🕊️',text:"Peace isn't found by rearranging circumstances. It's found by rearranging your mind.",sub:'— inner peace'},
{type:'quote',emoji:'🌺',text:"You don't need to earn the right to rest. You need rest because you are human.",sub:'— rest freely'},
{type:'quote',emoji:'🌷',text:"Kindness to yourself isn't selfish. It's the foundation everything else is built on.",sub:'— self-kindness'},
{type:'quote',emoji:'☁️',text:"Not every chapter needs to be exciting. Some chapters are about quiet healing.",sub:'— quiet chapters'},
{type:'quote',emoji:'🌿',text:"You can hold space for both grief and gratitude. They're not opposites.",sub:'— both and'},
{type:'quote',emoji:'💐',text:"The right people won't make you feel wrong for being yourself.",sub:'— your people exist'},
{type:'quote',emoji:'🌼',text:"It's okay to not know what you want yet. Figuring it out IS the journey.",sub:'— exploring'},
{type:'quote',emoji:'🍃',text:"Not every day needs a purpose. Some days just need a nap and a snack.",sub:'— soft days'},
{type:'quote',emoji:'🌱',text:"You've already come so far. Look back and see the distance. Be proud.",sub:'— look how far'},
{type:'quote',emoji:'🪴',text:"Worry is a misuse of imagination. Daydream instead.",sub:'— choose daydreams'},
{type:'quote',emoji:'🌾',text:"Slow mornings are a luxury. Protect them fiercely.",sub:'— morning ritual'},
{type:'quote',emoji:'🍂',text:"Your story doesn't need an audience to be meaningful.",sub:'— private magic'},
{type:'quote',emoji:'⭐',text:"Every expert was once a beginner who refused to quit.",sub:'— keep learning'},
{type:'quote',emoji:'🌟',text:"You don't have to be fearless. Just be willing to try while scared.",sub:'— courage'},
{type:'quote',emoji:'💛',text:"Happiness isn't a destination. It's the little moments you almost missed.",sub:'— notice them'},
{type:'quote',emoji:'🌈',text:"You are the author. If you don't like the chapter, write a new one.",sub:'— plot twist'},
{type:'quote',emoji:'🦋',text:"Transformation requires discomfort. The cocoon isn't comfortable either.",sub:'— necessary pain'},
{type:'quote',emoji:'🌙',text:"Some people won't understand your path. That's fine. It's not their path.",sub:'— your road'},
{type:'quote',emoji:'💫',text:"The universe keeps sending you lessons until you learn them. Pay attention.",sub:'— listen closely'},
{type:'quote',emoji:'🌸',text:"Celebrate the small things. You got up today. You're trying. That's huge.",sub:'— celebrate you'},
{type:'quote',emoji:'✨',text:"Sometimes the bravest thing you can do is ask for help.",sub:'— brave enough'},
{type:'quote',emoji:'🕊️',text:"You are not your worst day. You are not your biggest mistake. You are whole.",sub:'— whole'},
// ===== QUOTES - YOUR GOALS & DREAMS (51-120) =====
{type:'quote',emoji:'📖',text:"Those four novels in your head? They're waiting for you. No rush. Just one word at a time.",sub:'— the stories will come'},
{type:'quote',emoji:'🎙️',text:"Start the podcast. Share those stories. Even if only three people listen — those three people needed to hear you.",sub:'— your voice matters'},
{type:'quote',emoji:'🌊',text:"You don't need subscribers to validate your creativity. You create because it fills YOU up.",sub:"— art for art's sake"},
{type:'quote',emoji:'🏖️',text:"Plan that vacation. Even if it's months away. Give yourself something beautiful to look forward to.",sub:'— you deserve rest'},
{type:'quote',emoji:'💭',text:"Daydream freely. Those imaginary worlds in your head are not a waste of time — they're your superpower.",sub:'— imagination is magic'},
{type:'quote',emoji:'🌤️',text:"The right job is coming. One where you feel valued, where Monday doesn't feel like a punishment.",sub:'— it exists, keep looking'},
{type:'quote',emoji:'🎨',text:"Your hobby is yours. It doesn't have to make money. It doesn't have to impress anyone. It just has to make you happy.",sub:'— no monetization needed'},
{type:'quote',emoji:'📵',text:"Social media is a highlight reel of fiction. Your real life — messy, quiet, imperfect — is the actual story worth living.",sub:'— stay present'},
{type:'quote',emoji:'🧘',text:"You don't have to become a millionaire from what you love. Sometimes love is enough.",sub:'— redefine success'},
{type:'quote',emoji:'🌻',text:'Write for yourself. Create for yourself. The audience is a bonus, not the goal.',sub:'— create freely'},
{type:'quote',emoji:'📝',text:"That novel won't write itself but it also doesn't need to be written in a day. One paragraph. That's a victory.",sub:'— tiny progress'},
{type:'quote',emoji:'🎧',text:"Record that first episode. It'll be imperfect and wonderful. Everything good starts rough.",sub:'— start messy'},
{type:'quote',emoji:'✈️',text:"Save for that trip. Even $5 a week. Your future self sipping coffee somewhere beautiful will thank you.",sub:'— future you'},
{type:'quote',emoji:'🖊️',text:"Writer's block isn't failure. It's your brain composting. The words will come when they're ready.",sub:'— composting ideas'},
{type:'quote',emoji:'🎭',text:"You don't need permission to reinvent yourself. Do it as many times as you need.",sub:'— reinvention'},
{type:'quote',emoji:'🗺️',text:"The job you want exists. Maybe it hasn't found you yet. But it exists. Keep being findable.",sub:'— stay visible'},
{type:'quote',emoji:'📚',text:"Every book you've ever loved was once a messy first draft. Yours will be too. And it'll be beautiful.",sub:'— messy first'},
{type:'quote',emoji:'🎬',text:"Start before you're ready. Publish before it's perfect. Create before you feel qualified. That's how it's done.",sub:'— just start'},
{type:'quote',emoji:'🌅',text:"The vacation doesn't have to be expensive. A weekend somewhere green. A day by water. That counts.",sub:'— micro adventures'},
{type:'quote',emoji:'💌',text:"Write the story only you can tell. Nobody else has lived your life. That's what makes it special.",sub:'— only you'},
{type:'quote',emoji:'🎵',text:"Creativity isn't a competition. There's room for everyone's art. Including yours.",sub:'— no competition'},
{type:'quote',emoji:'📱',text:"Every hour off social media is an hour returned to your real life. That's not missing out — that's showing up.",sub:'— show up for you'},
{type:'quote',emoji:'🪁',text:"Let your ideas fly without judging where they land. Not everything needs to be productive.",sub:'— play freely'},
{type:'quote',emoji:'🌱',text:"The career you want might not look like anyone else's. That's okay. Build your own ladder.",sub:'— custom path'},
{type:'quote',emoji:'📓',text:"Chapter one doesn't need to be perfect. It just needs to exist. Write it badly. Then write it again.",sub:'— terrible first drafts'},
{type:'quote',emoji:'🎤',text:"Your stories deserve air. Even if your voice shakes. Even if nobody claps. You spoke. That's power.",sub:'— speak anyway'},
{type:'quote',emoji:'🏝️',text:"Rest is productive. A vacation isn't earned through suffering. You deserve it just because.",sub:'— just because'},
{type:'quote',emoji:'💡',text:"That idea you've been sitting on? It's not going to execute itself. But one small action today moves it forward.",sub:'— tiny action'},
{type:'quote',emoji:'🎨',text:"Art doesn't need to be consumed by others to be valid. A painting in your room is still art.",sub:'— private art'},
{type:'quote',emoji:'📖',text:"You have four novels in you. That's four worlds nobody else can create. What a beautiful burden.",sub:'— beautiful burden'},
{type:'quote',emoji:'🎙️',text:"Episode 1 doesn't need 10,000 downloads. It needs to exist. That's the hardest part. Do the hardest part.",sub:'— do the hard part'},
{type:'quote',emoji:'🌊',text:"Unplug. The internet will still be there tomorrow. Your peace of mind might not be.",sub:'— unplug today'},
{type:'quote',emoji:'✨',text:"You're allowed to pursue joy that doesn't pay. Joy IS the payment.",sub:'— joy as currency'},
{type:'quote',emoji:'📝',text:"Write the words even when they feel wrong. Editing is for later. Creating is for now.",sub:'— create now'},
{type:'quote',emoji:'🗺️',text:"Dream about that trip. Research the hotels. Look at the photos. Anticipation is half the joy.",sub:'— anticipate joy'},
{type:'quote',emoji:'🎧',text:"The podcast can be 10 minutes long. It can be about anything. It just needs your voice.",sub:'— your voice enough'},
{type:'quote',emoji:'💭',text:"Daydreaming is your brain doing creative work. Protect that time. It's not laziness.",sub:'— creative work'},
{type:'quote',emoji:'🌟',text:"A fulfilling job isn't about salary alone. It's about waking up without dread. That exists for you.",sub:'— no more dread'},
{type:'quote',emoji:'📵',text:"Likes don't equal worth. Followers don't equal friends. Shares don't equal impact. Live offline.",sub:'— live real'},
{type:'quote',emoji:'🎨',text:"Create like nobody's watching. Because honestly? They're all watching their own screens anyway.",sub:'— unobserved art'},
{type:'quote',emoji:'📚',text:"Read the books. Write the words. Share the thoughts. Not for fame. For the quiet joy of expression.",sub:'— quiet joy'},
{type:'quote',emoji:'🌸',text:"Your creative life doesn't need a business plan. It needs your attention. That's it.",sub:'— just attention'},
{type:'quote',emoji:'✈️',text:"Book the trip. Buy the journal. Start the project. Future you is already grateful.",sub:'— future gratitude'},
{type:'quote',emoji:'🎭',text:"You can be a completely different person next year. Nobody is stopping you except yesterday's habits.",sub:'— break free'},
{type:'quote',emoji:'💫',text:"Success looks different for everyone. Yours might be a quiet life with books and tea. That's perfect.",sub:'— quiet success'},
{type:'quote',emoji:'📓',text:"Four novels. Four worlds living rent-free in your mind. Pay them attention — they're trying to be born.",sub:'— let them out'},
{type:'quote',emoji:'🎤',text:"The podcast isn't about being famous. It's about the relief of finally sharing what's inside you.",sub:'— sweet relief'},
{type:'quote',emoji:'🏖️',text:"You work hard. A vacation isn't a reward — it's a right. Take it.",sub:'— your right'},
{type:'quote',emoji:'🌻',text:"When creativity feels hard, remember: you're not performing. You're playing. Let it be play.",sub:'— play mode'},
{type:'quote',emoji:'📱',text:"Three days off Instagram. Try it. Watch how much time you suddenly have for yourself.",sub:'— try three days'},
// ===== QUOTES - DEEP & POETIC (121-200) =====
{type:'quote',emoji:'🌙',text:"You are the poem someone hasn't written yet. You are the song playing in a distant café at 3 PM.",sub:'— you are art'},
{type:'quote',emoji:'🦢',text:'Softness is not weakness. The gentlest rain feeds the deepest roots.',sub:'— stay soft'},
{type:'quote',emoji:'🪷',text:"You carry storms inside you, and yet you bloom. That's not nothing — that's everything.",sub:'— resilience'},
{type:'quote',emoji:'🌸',text:"One day this heaviness will lift, and you'll look back and be so proud of yourself for staying.",sub:'— keep going'},
{type:'quote',emoji:'💫',text:"The universe didn't make a mistake with you. You are the exact shape the world needed.",sub:'— on purpose'},
{type:'quote',emoji:'🕯️',text:"Even on your dimmest days, you are someone's warmth. Remember that.",sub:'— your light'},
{type:'quote',emoji:'🌿',text:'Growth happens in silence. In the quiet days. In the doing-nothing-but-surviving days. That counts too.',sub:'— quiet growth'},
{type:'quote',emoji:'🫧',text:"Let the things that don't serve you float away like bubbles. You don't have to hold everything.",sub:'— release'},
{type:'quote',emoji:'🌈',text:"After every overwhelm comes a clearing. You're closer to it than you think.",sub:'— almost there'},
{type:'quote',emoji:'🪻',text:"You are not your productivity. You are not your job title. You are the person who notices sunsets. That's enough.",sub:'— enough'},
{type:'quote',emoji:'🌊',text:"The ocean doesn't apologize for its depth. Neither should you.",sub:'— unapologetic depth'},
{type:'quote',emoji:'🌙',text:"You were born under the same stars that ancient poets wrote about. You belong here as much as they did.",sub:'— ancient belonging'},
{type:'quote',emoji:'🦋',text:"Metamorphosis doesn't ask for permission. It just begins. Maybe yours already has.",sub:'— already changing'},
{type:'quote',emoji:'🌸',text:"There's a version of you that's already healed. She's waiting. She's patient. She knows you'll arrive.",sub:'— she's waiting'},
{type:'quote',emoji:'💫',text:"You are made of the same atoms that once formed stars. You are literally cosmic. Act like it.",sub:'— stardust'},
{type:'quote',emoji:'🕯️',text:"Not all storms come to destroy. Some come to clear the path ahead.",sub:'— clearing storms'},
{type:'quote',emoji:'🌿',text:"You are the softest and strongest thing. Like water. Like moonlight. Like a story told in whispers.",sub:'— soft power'},
{type:'quote',emoji:'🫧',text:"Breathe like the tide. In and out. No rush. The shore will always be there.",sub:'— tidal breath'},
{type:'quote',emoji:'🌙',text:"Some flowers bloom at night. Maybe you're one of them. Maybe your time is the quiet hours.",sub:'— night bloomer'},
{type:'quote',emoji:'🌸',text:"You don't need fixing. You need gentleness. You need someone to say 'I see you' and mean it.",sub:'— I see you'},
{type:'quote',emoji:'💫',text:"Your sensitivity isn't a flaw. It's how you read the room, feel the art, love the deeply.",sub:'— sensitive gift'},
{type:'quote',emoji:'🦢',text:"Grace isn't about being perfect. It's about being gentle with yourself while you figure it out.",sub:'— messy grace'},
{type:'quote',emoji:'🌊',text:"Rivers don't force their way. They find it. You will too.",sub:'— find the way'},
{type:'quote',emoji:'🕯️',text:"You are both the storm and the shelter. The question and the answer. Complete already.",sub:'— complete'},
{type:'quote',emoji:'🌙',text:"In the quiet between breaths, there you are. Whole. Still. Enough.",sub:'— between breaths'},
{type:'quote',emoji:'🌸',text:"What if the cracks are where the light enters? What if broken is just another word for open?",sub:'— broken open'},
{type:'quote',emoji:'💫',text:"You are the answer to a question the universe asked billions of years ago.",sub:'— cosmic answer'},
{type:'quote',emoji:'🦋',text:"Not all wings are visible. Yours are made of everything you've survived.",sub:'— invisible wings'},
{type:'quote',emoji:'🌿',text:"Time moves in circles, not lines. You'll get another chance. And another. And another.",sub:'— circles'},
{type:'quote',emoji:'🫧',text:"Let yourself dissolve into this moment. Just this one. Everything else can wait.",sub:'— this moment'},
{type:'quote',emoji:'🌙',text:"The moon doesn't compete with the sun. It just shines when it's its turn. Your turn is coming.",sub:'— your turn'},
{type:'quote',emoji:'🌸',text:"Somewhere in a parallel universe, you're already living the dream. This version of you is catching up.",sub:'— catching up'},
{type:'quote',emoji:'💫',text:"You don't need to shine brightly every day. Even dim stars are still stars.",sub:'— dim star'},
{type:'quote',emoji:'🕯️',text:"The weight you carry was never yours alone. Put some of it down. The world won't collapse.",sub:'— put it down'},
{type:'quote',emoji:'🦢',text:"You move through life like water through silk. Graceful even when you don't feel it.",sub:'— graceful'},
{type:'quote',emoji:'🌊',text:"The deepest oceans are the quietest. Your depth is not a burden — it's a treasure.",sub:'— your depth'},
{type:'quote',emoji:'🌙',text:"Some truths only come in silence. Sit with the quiet. Let it speak.",sub:'— listen to silence'},
{type:'quote',emoji:'🌸',text:"You are a love letter the universe wrote to itself.",sub:'— love letter'},
{type:'quote',emoji:'💫',text:"Not all who wander are lost. Some are just collecting stories.",sub:'— collecting stories'},
{type:'quote',emoji:'🦋',text:"You've been the phoenix before. You know how this works. Rise again.",sub:'— rise again'},
{type:'quote',emoji:'🌿',text:"Roots grow deepest in the hardest soil. You are growing deep.",sub:'— deep roots'},
{type:'quote',emoji:'🫧',text:"Impermanence is freedom. Nothing lasts forever — not even this hard season.",sub:'— impermanence'},
{type:'quote',emoji:'🌙',text:"The night sky needed darkness to show off its stars. Maybe your darkness has a purpose too.",sub:'— purposeful dark'},
{type:'quote',emoji:'🌸',text:"You are poetry in motion. Every stumble, every rise, every breath — it's all part of the verse.",sub:'— poetry in motion'},
{type:'quote',emoji:'💫',text:"Be the energy you want to attract. Quiet. Soft. Certain. Warm.",sub:'— attract softly'},
{type:'quote',emoji:'🕯️',text:"There's a light in you that no amount of tired can extinguish. It's still there. I promise.",sub:'— still burning'},
{type:'quote',emoji:'🦢',text:"Elegance is knowing what not to say. Wisdom is knowing what not to carry.",sub:'— elegant wisdom'},
{type:'quote',emoji:'🌊',text:"You are the calm within your own chaos. Find that center. It never left.",sub:'— your center'},
{type:'quote',emoji:'🌙',text:"Sleep well tonight knowing you did enough today. You did. Even if it doesn't feel like it.",sub:'— you did enough'},
{type:'quote',emoji:'🌸',text:"Every ending you've survived has made you fluent in new beginnings.",sub:'— fluent in fresh starts'},
{type:'quote',emoji:'💫',text:"The most beautiful version of you isn't in the future. It's the one reading this right now.",sub:'— right now'},
{type:'quote',emoji:'🦋',text:"Let yourself exist without performing. You don't need to be entertaining to be lovable.",sub:'— exist freely'},
{type:'quote',emoji:'🌿',text:"Sometimes the universe says 'not yet' because something better is being arranged.",sub:'— not yet'},
{type:'quote',emoji:'🫧',text:"You are both the artist and the masterpiece. Still being painted. Still beautiful.",sub:'— work in progress'},
{type:'quote',emoji:'🌙',text:"Rest your eyes. Rest your mind. Rest your need to be perfect. Just rest.",sub:'— just rest'},
{type:'quote',emoji:'🕯️',text:"Gentleness is a revolution in a world that demands you be hard. Stay gentle.",sub:'— gentle revolution'},
{type:'quote',emoji:'🌸',text:"You've bloomed in conditions that should have destroyed you. Never forget that strength.",sub:'— impossible bloom'},
{type:'quote',emoji:'💫',text:"One day someone will love you the way you love rainy days — completely, quietly, deeply.",sub:'— love like rain'},
{type:'quote',emoji:'🦢',text:"You don't need to justify your existence with accomplishments. Existing is enough.",sub:'— existence'},
{type:'quote',emoji:'🌊',text:"The tide always returns. So will your motivation. So will your joy. Give it time.",sub:'— the tide returns'},
// ===== VIBES - SCENES TO IMAGINE (201-320) =====
{type:'vibe',emoji:'🏖️',text:'Imagine: a small café by the sea. A worn paperback in your hands. Wind chimes singing softly. Salt breeze in your hair. You have nowhere to be.',sub:'— breathe in, breathe out'},
{type:'vibe',emoji:'📚',text:'Picture this: a cozy bookshop on a rainy afternoon. Warm lighting. The smell of old pages. A cat sleeping on the counter. You belong here.',sub:'— find your peace'},
{type:'vibe',emoji:'🌅',text:"You're on a rooftop at golden hour. The city hums below. A warm cup in your hands. The sky is painted just for you.",sub:'— this moment is yours'},
{type:'vibe',emoji:'🌸',text:'A cherry blossom path in spring. Petals drifting like snow. Soft footsteps. No destination. Just wandering, just being.',sub:'— slow down'},
{type:'vibe',emoji:'🏔️',text:'A mountain temple at dawn. Mist rolling through the valley. Silence so pure it feels like a prayer. You are at peace.',sub:'— serenity'},
{type:'vibe',emoji:'🌙',text:'A night garden. Fireflies dancing. The moon reflected in still water. You sit by the edge, finally breathing easy.',sub:'— let the night hold you'},
{type:'vibe',emoji:'☕',text:"A window seat on a train. Green hills scrolling by. Tea going cold because you're lost in thought. And that's perfectly fine.",sub:'— wander freely'},
{type:'vibe',emoji:'🪴',text:'Your dream apartment. Plants everywhere. Sunlight pooling on wooden floors. A half-written novel on the desk. No deadlines. Just you.',sub:'— someday soon'},
{type:'vibe',emoji:'🌊',text:"Bare feet in warm sand. Waves whispering. The horizon stretches endlessly. You don't need answers right now. Just this.",sub:'— just breathe'},
{type:'vibe',emoji:'🕯️',text:"A candlelit room. Soft music playing. Rain against the window. A blanket, a journal, a quiet evening that's all yours.",sub:"— you're safe here"},
{type:'vibe',emoji:'🏮',text:'Lanterns floating on dark water. Each one carries a worry away into the night. Watch them go. You are lighter now.',sub:'— let go'},
{type:'vibe',emoji:'🎋',text:'A bamboo forest at twilight. Light filtering through in golden threads. The world is quiet here. You can hear yourself think.',sub:'— clarity'},
{type:'vibe',emoji:'🦢',text:'A jade pond in a hidden garden. Cranes folding through the air. Time moves differently here — slowly, gently, for you.',sub:'— slow time'},
{type:'vibe',emoji:'🏯',text:'An ancient temple floating above the clouds. Gold bells chiming with the wind. You sit at the edge, legs dangling over infinity.',sub:'— above it all'},
{type:'vibe',emoji:'🐉',text:'A dragon sleeping beneath a crystal lake. You can see its breath making the surface shimmer. Everything is ancient and safe here.',sub:'— ancient safety'},
{type:'vibe',emoji:'🌙',text:'Moonlight pouring through a paper window. The smell of jasmine tea. A brush and ink waiting. This evening belongs to you.',sub:'— creative night'},
{type:'vibe',emoji:'🪷',text:'A lotus pond at dawn. Pink petals opening as the sun touches them. You are watching the world wake up gently.',sub:'— gentle awakening'},
{type:'vibe',emoji:'🏮',text:'A night market. Warm golden light. Steam rising from food stalls. Laughter you can feel in your chest. You are alive.',sub:'— alive'},
{type:'vibe',emoji:'🌸',text:'A palace garden in perpetual spring. Wisteria hanging like purple rain. A stone bench with your name on it.',sub:'— your bench'},
{type:'vibe',emoji:'☁️',text:'Lying in a field of white flowers, watching clouds become dragons and castles. Your mind has nowhere to be.',sub:'— cloudwatching'},
{type:'vibe',emoji:'🌊',text:'A cliffside overlooking a turquoise sea. Wind in your hair. Salt on your lips. Nothing to do except exist.',sub:'— edge of the world'},
{type:'vibe',emoji:'📚',text:'A library with no end. Shelves stretching into golden light. Every book is a world waiting. You have infinite time.',sub:'— infinite stories'},
{type:'vibe',emoji:'🌅',text:'Standing in a field of lavender at sunset. Purple stretching to the horizon. The warmth on your skin is a hug.',sub:'— lavender sunset'},
{type:'vibe',emoji:'🏮',text:'Paper lanterns rising into a star-filled sky. Each one a released thought. Watch them climb higher, higher, gone.',sub:'— rising thoughts'},
{type:'vibe',emoji:'☕',text:'A café in a small mountain town. Snow outside the window. Hot chocolate between your palms. A book you love.',sub:'— mountain café'},
{type:'vibe',emoji:'🌙',text:'A rooftop garden at midnight. Fairy lights tangled through trellises. The city asleep below. This silence is yours.',sub:'— midnight garden'},
{type:'vibe',emoji:'🐉',text:'Flying on the back of a gentle dragon. Below: mountains, rivers, tiny villages with warm lights. You are weightless.',sub:'— weightless'},
{type:'vibe',emoji:'🏯',text:'A courtyard with a plum tree. Petals in your tea. A old woman tells you a story. You are the story.',sub:'— you are the story'},
{type:'vibe',emoji:'🌸',text:'Walking through a tunnel of cherry blossoms. Pink light everywhere. Soft as a dream. This is the dream.',sub:'— pink tunnel'},
{type:'vibe',emoji:'🪷',text:'A koi pond so clear you can see the bottom. Gold and white fish circling lazily. You have all the time.',sub:'— koi peace'},
{type:'vibe',emoji:'☁️',text:'Floating on your back in a warm spring. Steam rising around you. Mountains in every direction. Total surrender.',sub:'— total surrender'},
{type:'vibe',emoji:'🌊',text:'An underwater palace. Light filtering through blue. Everything moves slowly here. Sound is muffled. Peace is absolute.',sub:'— underwater peace'},
{type:'vibe',emoji:'🏮',text:'A bridge over a glowing river at night. Each stone beneath your feet is warm. On the other side: something good.',sub:'— crossing over'},
{type:'vibe',emoji:'🌙',text:'A bedroom with a skylight. Stars visible through the glass. Your favorite music playing softly. Drifting, drifting.',sub:'— drifting off'},
{type:'vibe',emoji:'🌸',text:'A hilltop of wild flowers. You can see the ocean from here. The wind smells like freedom. Run if you want.',sub:'— freedom hill'},
{type:'vibe',emoji:'☕',text:'A rain-soaked terrace. Jasmine growing up the walls. A warm drink, a soft blanket, a good story on your phone.',sub:'— rainy comfort'},
{type:'vibe',emoji:'🏯',text:'A traditional room with sliding doors open to a garden. A wind chime singing. Incense spiraling. Complete stillness.',sub:'— complete stillness'},
{type:'vibe',emoji:'🐉',text:'A valley where dragons nest. Their breath makes the air warm. Mist curls around mountains. You are protected here.',sub:'— dragon valley'},
{type:'vibe',emoji:'🌅',text:'A pier at the quietest hour. The sun hasn't risen yet. The world belongs only to you and the gulls.',sub:'— before dawn'},
{type:'vibe',emoji:'🪴',text:'A greenhouse full of tropical plants. Humidity kisses your skin. Butterflies drift past. Time is honey here.',sub:'— greenhouse time'},
{type:'vibe',emoji:'🏮',text:'A courtyard strung with silk lanterns. A musician plays something soft. You are wearing your finest robes. Tonight is for joy.',sub:'— silk lantern night'},
{type:'vibe',emoji:'🌙',text:'The aurora borealis reflected in a still lake. Green and purple dancing. You watch in silence. Some beauty needs no words.',sub:'— aurora silence'},
{type:'vibe',emoji:'🌸',text:'A secret garden behind a crumbling wall. Roses and ivy reclaiming everything. Nature knows how to heal. So do you.',sub:'— secret garden'},
{type:'vibe',emoji:'☕',text:'A hole-in-the-wall café that only you know about. The owner remembers your order. The chair by the window is always free.',sub:'— your secret place'},
{type:'vibe',emoji:'🌊',text:'A lighthouse on a cliff. Waves crashing below. Inside: warmth, books, tea. The storm is outside. You are inside.',sub:'— lighthouse safety'},
{type:'vibe',emoji:'📚',text:'A reading nook built into a tree. Cushions, fairy lights, a stack of unread books. Rain pattering on leaves above.',sub:'— treehouse reading'},
{type:'vibe',emoji:'🏮',text:'A floating village at dusk. Boats gently rocking. Someone is cooking nearby. The smell of home in a place you\'ve never been.',sub:'— found home'},
{type:'vibe',emoji:'🌙',text:'A palace made of moonlight. Everything silver and soft. You are the guest of honor. You are always welcome here.',sub:'— moonlight palace'},
{type:'vibe',emoji:'🌸',text:'Pink mountains at sunrise. Clouds you could touch. A path only you can walk. Where does it lead? Anywhere you want.',sub:'— your path'},
{type:'vibe',emoji:'☁️',text:'A hammock between two cherry trees. Petals falling on you like confetti. The celebration is just being alive.',sub:'— celebration'},
{type:'vibe',emoji:'🐉',text:'A crystal cave. Geodes glowing purple and blue. Water dripping echoes. In the deepest part: a dragon guarding your peace.',sub:'— guarded peace'},
{type:'vibe',emoji:'🏯',text:'Snow falling on a temple roof. Everything muffled. Everything soft. A fire inside. Stories being told. You are warm.',sub:'— snow temple'},
{type:'vibe',emoji:'🌅',text:'The last five minutes of sunset. Gold dripping off everything. You know tomorrow will come. But right now — this gold.',sub:'— golden five minutes'},
{type:'vibe',emoji:'🌊',text:'A boat on a river so calm it mirrors the sky perfectly. You can't tell which way is up. Both ways are beautiful.',sub:'— mirror river'},
{type:'vibe',emoji:'🪷',text:'A garden where every flower is a kind word someone said to you. Look how large it is. You are more loved than you know.',sub:'— word garden'},
{type:'vibe',emoji:'🏮',text:'An old bookshop in a lantern-lit alley. The shopkeeper nods. The right book finds you. It always does.',sub:'— the right book'},
{type:'vibe',emoji:'☕',text:'First rain of the season. Petrichor. A window cracked open. A warm cup. Everything made new. Everything possible.',sub:'— first rain'},
{type:'vibe',emoji:'🌙',text:'A music box playing in an empty room. Moonlight through lace curtains. Someone once danced here. Maybe you will too.',sub:'— dance alone'},
{type:'vibe',emoji:'🌸',text:'An endless field of cosmos flowers. Pink and white against blue sky. You're walking through a painting. You are the painting.',sub:'— you are the painting'},
// ===== BREATHING EXERCISES (321-380) =====
{type:'breathe',emoji:'🌬️',text:"Let's pause for a moment. Breathe in slowly... hold... breathe out gently. You're doing so well.",sub:'— 4 in, 4 hold, 4 out'},
{type:'breathe',emoji:'🫧',text:'Close your eyes. Imagine petals falling around you. Each exhale releases something heavy. Let it go.',sub:'— release with each breath'},
{type:'breathe',emoji:'🌸',text:'Inhale: "I am enough." Exhale: "I release what isn\'t mine to carry." Repeat until you believe it.',sub:'— you are enough'},
{type:'breathe',emoji:'☁️',text:"Breathe like the wind through cherry blossoms. Gentle. Effortless. You don't have to try so hard.",sub:'— easy does it'},
{type:'breathe',emoji:'🌙',text:"Three deep breaths. That's all. In through your nose... out through your mouth... one more... there you go.",sub:'— a gift to yourself'},
{type:'breathe',emoji:'🌊',text:"Imagine each inhale is a wave coming in. Each exhale, it retreats. You are the shore. Steady. Constant.",sub:'— be the shore'},
{type:'breathe',emoji:'🕯️',text:"Breathe in warmth. Breathe out tension. Feel your shoulders drop. Feel your jaw unclench. There.",sub:'— unclench'},
{type:'breathe',emoji:'🌿',text:"Inhale for 4... hold for 4... exhale for 6. The longer exhale tells your body: you're safe.",sub:'— you are safe'},
{type:'breathe',emoji:'🪷',text:"Picture a lotus opening with each inhale. Closing gently with each exhale. You are that flower.",sub:'— lotus breath'},
{type:'breathe',emoji:'☁️',text:"Breathe like you're blowing on hot tea. Gentle. Slow. Patient. There's no rush here.",sub:'— tea breath'},
{type:'breathe',emoji:'🌙',text:"Inhale starlight. Exhale worry. Inhale peace. Exhale noise. Inhale yourself back to yourself.",sub:'— come home'},
{type:'breathe',emoji:'🫧',text:"Each breath is a tiny reset. You've just reset. And again. And again. Brand new, every time.",sub:'— constant renewal'},
{type:'breathe',emoji:'🌸',text:"Put your hand on your chest. Feel that? That's your heart. It hasn't stopped fighting for you. Breathe with it.",sub:'— your loyal heart'},
{type:'breathe',emoji:'🌊',text:"Imagine breathing underwater. Slow and dreamlike. Everything muffled. Everything soft. You are suspended in peace.",sub:'— underwater breath'},
{type:'breathe',emoji:'🌬️',text:"Breathe in through your nose: smell rain. Breathe out through your mouth: release the day.",sub:'— rain release'},
{type:'breathe',emoji:'🕯️',text:"Inhale: gather all the good moments from today. Exhale: let go of everything that hurt.",sub:'— gather and release'},
{type:'breathe',emoji:'🌿',text:"Your breath is the one thing that's always with you. Always available. Always free. Use it now.",sub:'— always available'},
{type:'breathe',emoji:'🪷',text:"Seven breaths. Just seven. Count them on your fingers. By the last one, something will have shifted.",sub:'— seven breaths'},
{type:'breathe',emoji:'☁️',text:"Imagine you're a cloud. Formless. Soft. Drifting. Nothing to do. Nowhere to be. Just floating.",sub:'— cloud drift'},
{type:'breathe',emoji:'🌙',text:"The world asks so much of you. Right now, ask nothing of yourself. Just breathe. Just be.",sub:'— ask nothing'},
{type:'breathe',emoji:'🫧',text:"Breathe in possibility. Breathe out limitation. You are more vast than any worry you carry.",sub:'— vast'},
{type:'breathe',emoji:'🌸',text:"Close your eyes. Feel the ground beneath you. It's holding you up. It always has. It always will.",sub:'— grounded'},
{type:'breathe',emoji:'🌊',text:"Match your breathing to the ocean. Slow. Rhythmic. Eternal. You are part of something bigger.",sub:'— ocean rhythm'},
{type:'breathe',emoji:'🌬️',text:"Exhale longer than you inhale. Count to 4 in, count to 7 out. That extra space is freedom.",sub:'— longer exhale'},
{type:'breathe',emoji:'🕯️',text:"Imagine breathing in golden light. It fills every tired part of you. You are being refilled.",sub:'— golden refill'},
{type:'breathe',emoji:'🌿',text:"Touch something near you. Feel its texture. Now breathe. Sensation and breath together — this is presence.",sub:'— sensory presence'},
{type:'breathe',emoji:'🪷',text:"In... 2... 3... 4... Hold... 2... 3... 4... Out... 2... 3... 4... 5... 6... Again? Let's go again.",sub:'— box breath'},
{type:'breathe',emoji:'☁️',text:"You don't need an app for this. You don't need a timer. Just breathe gently and trust your body knows how.",sub:'— trust your body'},
{type:'breathe',emoji:'🌙',text:"Soften your eyes. Soften your hands. Soften your thoughts. Breathe into the softness.",sub:'— soften everything'},
{type:'breathe',emoji:'🌸',text:"Imagine each breath painting color in the air. What color is your calm? Breathe that color in.",sub:'— color breathing'},
{type:'breathe',emoji:'🌊',text:"The anxiety will pass. It always does. But right now: breathe. One breath. Then another. That's all you need to do.",sub:'— one at a time'},
{type:'breathe',emoji:'🌬️',text:"Notice five things you can see. Four you can touch. Three you can hear. Two you can smell. One you can taste. Breathe.",sub:'— 5-4-3-2-1'},
{type:'breathe',emoji:'🫧',text:"You are alive. Right now. In this moment. That is a miracle worth one deep breath of appreciation.",sub:'— alive miracle'},
{type:'breathe',emoji:'🕯️',text:"Light a candle in your mind. Watch the flame flicker with your breath. Steady it. Steady yourself.",sub:'— candle gazing'},
{type:'breathe',emoji:'🌿',text:"Your nervous system is listening. Tell it: slow down. Tell it: we're safe. It believes you. Breathe.",sub:'— talk to your body'},
{type:'breathe',emoji:'🪷',text:"Imagine roots growing from your feet into the earth. With each breath, they grow deeper. You are anchored.",sub:'— root down'},
{type:'breathe',emoji:'☁️',text:"Nowhere to go. Nothing to fix. No one to be. Just this breath. Just this moment. Just you.",sub:'— just you'},
{type:'breathe',emoji:'🌙',text:"The exhale is where the magic happens. It's where you let go. Make it long. Make it slow. Let go.",sub:'— magic exhale'},
{type:'breathe',emoji:'🌸',text:"Three breaths for the morning. Three for the afternoon. Three for the night. Nine gifts you give yourself daily.",sub:'— nine gifts'},
{type:'breathe',emoji:'🌊',text:"You are not drowning. You are learning to swim. And right now, you're floating. That's enough. Float.",sub:'— float'},
// ===== JOKES & LIGHT (381-500) =====
{type:'joke',emoji:'🐱',text:'Even cats take 16 hours of naps and everyone still adores them. Be the cat.',sub:'— nap without guilt'},
{type:'joke',emoji:'🧁',text:"Fun fact: you're doing better than every plant I've ever owned. And I loved those plants.",sub:'— thriving'},
{type:'joke',emoji:'🦦',text:"Otters hold hands when they sleep so they don't drift apart. Consider this me holding your hand right now.",sub:"— you're not alone"},
{type:'joke',emoji:'🐸',text:"Frogs don't overthink jumping into ponds. Sometimes you just gotta leap and splash.",sub:'— splash away'},
{type:'joke',emoji:'🍵',text:"You're like a perfect cup of tea — some people just aren't ready for your warmth, and that's their loss.",sub:'— stay warm'},
{type:'joke',emoji:'🦋',text:'Plot twist: the caterpillar literally dissolves into goo before becoming a butterfly. Your messy phase is transformation.',sub:'— glow up loading'},
{type:'joke',emoji:'🧸',text:'Your childhood self would be SO impressed that you can eat ice cream whenever you want now.',sub:'— small victories'},
{type:'joke',emoji:'🐧',text:"Penguins propose with pebbles. The bar is literally on the floor. You're doing fine.",sub:'— low bar energy'},
{type:'joke',emoji:'🌮',text:"Bad day? At least you're not a taco that fell apart. But even if you are, someone still loves a deconstructed taco.",sub:'— beautifully messy'},
{type:'joke',emoji:'🦥',text:"Sloths only poop once a week. So if your productivity is low today, you're still ahead of a sloth.",sub:'— ahead of sloths'},
{type:'joke',emoji:'🐶',text:"Dogs don't care about your job title. They're just happy you came home. Be someone's dog-level excitement.",sub:'— dog joy'},
{type:'joke',emoji:'🧀',text:"Cheese exists. That's reason enough to have a good day.",sub:'— cheese is reason'},
{type:'joke',emoji:'🐱',text:"Cats will literally knock things off tables just to feel something. You're allowed to shake things up too.",sub:'— knock things over'},
{type:'joke',emoji:'🌈',text:"If you were a crayon, you'd be the one everyone fights over. Probably the sparkly purple.",sub:'— sparkly you'},
{type:'joke',emoji:'🧁',text:"Life is short. Eat the cupcake. Take the nap. Watch the show. Not everything needs to be a learning experience.",sub:'— eat the cupcake'},
{type:'joke',emoji:'🐙',text:"Octopuses have three hearts and blue blood. And yet they still have bad days. You're allowed yours.",sub:'— three-heart day'},
{type:'joke',emoji:'🦋',text:"Butterflies taste with their feet. So technically, you're already more elegant than a butterfly.",sub:'— elegant you'},
{type:'joke',emoji:'🌻',text:"Sunflowers face the sun even on cloudy days. Some call it optimism. Others call it stubborn. Be both.",sub:'— stubborn optimism'},
{type:'joke',emoji:'🐧',text:"Baby penguins huddle together for warmth. This app is basically your digital huddle. Stay warm.",sub:'— digital huddle'},
{type:'joke',emoji:'🧸',text:"Plot twist: adulting has no final boss. You've been grinding side quests this whole time.",sub:'— side quests'},
{type:'joke',emoji:'🐶',text:"Your bed misses you. The pillows are worried. The blanket sent a text. Go home. Rest.",sub:'— bed misses you'},
{type:'joke',emoji:'🌮',text:"You know what's underrated? Doing absolutely nothing. Like a professional. With snacks.",sub:'— professional nothing'},
{type:'joke',emoji:'🦥',text:"Remember: you were once the fastest sperm. You've already won the most competitive race of your life.",sub:'— original winner'},
{type:'joke',emoji:'🐱',text:"Your anxiety is basically a very dramatic cat. Loud, unnecessary, but it means well. Pet it and move on.",sub:'— pet the anxiety'},
{type:'joke',emoji:'🧀',text:"Some days are a whole brie. Some days are string cheese. Both are valid forms of cheese. Both are you.",sub:'— cheese philosophy'},
{type:'joke',emoji:'🐙',text:"Fun fact: sea otters have a favorite rock they keep in a little pocket of skin. What's your favorite rock? Find it.",sub:'— pocket rock'},
{type:'joke',emoji:'🌈',text:"You're the WiFi password people want. Valuable. A little complicated. Worth the effort to figure out.",sub:'— worth the effort'},
{type:'joke',emoji:'🧁',text:"Today's vibe: existing peacefully like a cloud. Not going anywhere in particular. Just vibing.",sub:'— cloud vibes'},
{type:'joke',emoji:'🐶',text:"Dogs spin in circles before lying down and somehow that's not considered anxiety. You're fine.",sub:'— spin and rest'},
{type:'joke',emoji:'🦋',text:"Motivational speeches are cool but have you ever canceled plans? That's the real self-care.",sub:'— canceled plans'},
{type:'joke',emoji:'🌻',text:"You have the same number of hours as Beyoncé. But you also have the same need for sleep. Choose sleep.",sub:'— choose sleep'},
{type:'joke',emoji:'🐧',text:"If penguins can survive Antarctic winters by just standing around, you can survive this meeting.",sub:'— survive this'},
{type:'joke',emoji:'🧸',text:"Your future self is looking back at today and saying 'you had no idea how much better it was about to get.'",sub:'— spoiler alert'},
{type:'joke',emoji:'🐱',text:"Cat philosophy: if it doesn't bring you food, warmth, or entertainment, nap through it.",sub:'— nap philosophy'},
{type:'joke',emoji:'🌮',text:"Therapist: tell me about your week. Me: *gestures vaguely at everything*. Therapist: valid.",sub:'— valid gesture'},
{type:'joke',emoji:'🦥',text:"Your comfort zone called. It says it misses you and has snacks. It's okay to visit sometimes.",sub:'— comfort zone snacks'},
{type:'joke',emoji:'🐶',text:"A golden retriever doesn't question if it deserves love. It just shows up and expects it. Golden retriever energy.",sub:'— golden energy'},
{type:'joke',emoji:'🧀',text:"You're gouda enough. That's it. That's the pun. You smiled though, didn't you?",sub:'— cheesy but true'},
{type:'joke',emoji:'🐙',text:"Marine biologists say dolphins play for fun. Not for content. Not for engagement. Just play. Be dolphin.",sub:'— play for play'},
{type:'joke',emoji:'🌈',text:"Life hack: if you lower your expectations for today to 'survive and maybe snack,' you'll exceed them.",sub:'— exceed expectations'},
{type:'joke',emoji:'🧁',text:"Adulting is just googling how to do things and hoping for the best. You're not behind. Nobody knows.",sub:'— nobody knows'},
{type:'joke',emoji:'🐱',text:"If you're reading this, you're probably avoiding something. That's okay. Five more minutes. Then go do it.",sub:'— five more minutes'},
{type:'joke',emoji:'🦋',text:"Sharks have to keep swimming to breathe. You don't. You can stop. You're already more advanced than a shark.",sub:'— better than sharks'},
{type:'joke',emoji:'🌻',text:"Flowers don't bloom all year. Pizza doesn't judge you for ordering at midnight. Find comfort in these truths.",sub:'— midnight pizza'},
{type:'joke',emoji:'🐧',text:"Penguins sometimes push each other into the water to check for predators. At least your friends just send memes.",sub:'— good friends'},
{type:'joke',emoji:'🧸',text:"Your inner child just wants to color outside the lines and eat dinosaur nuggets. Maybe give them what they want today.",sub:'— dino nuggets'},
{type:'joke',emoji:'🐶',text:"A dog's entire life strategy is: love hard, nap often, get excited about walks. No notes.",sub:'— dog strategy'},
{type:'joke',emoji:'🌮',text:"Some days you're the piñata. Some days you're the kid with the stick. Today you're the candy falling out — sweet and everywhere.",sub:'— piñata day'},
{type:'joke',emoji:'🦥',text:"Remember: trees grow for decades before anyone climbs them. You're still growing. Stop climbing yourself.",sub:'— stop climbing'},
{type:'joke',emoji:'🐱',text:"My therapist said I need to stop comparing myself to others. So now I only compare myself to cats. I'm doing worse but happier.",sub:'— cat comparison'},
{type:'joke',emoji:'🧀',text:"The moon is just a rock and yet poets have written about it for centuries. You're infinitely more interesting than a rock.",sub:'— more than a rock'},
{type:'joke',emoji:'🐙',text:"Jellyfish have survived 650 million years without a brain. There's hope for all of us on Mondays.",sub:'— monday hope'},
{type:'joke',emoji:'🌈',text:"Your comfort show isn't childish. It's emotional regulation. Science. Watch it again.",sub:'— watch it again'},
{type:'joke',emoji:'🧁',text:"You don't need a spa day to relax. Sometimes a hot shower and three minutes of staring at a wall works just fine.",sub:'— wall staring spa'},
{type:'joke',emoji:'🐶',text:"Dogs get excited about THE SAME WALK every day. Maybe excitement isn't about novelty. Maybe it's about presence.",sub:'— same walk magic'},
{type:'joke',emoji:'🦋',text:"Technically, a nap is just a horizontal meditation. Namaste in bed.",sub:'— namasnooze'},
{type:'joke',emoji:'🌻',text:"If a bee's wings are too small for its body but it flies anyway, you can absolutely send that email.",sub:'— send the email'},
{type:'joke',emoji:'🐧',text:"Emperor penguins fast for 4 months straight. So if you ate three meals today, you're basically royalty.",sub:'— penguin royalty'},
{type:'joke',emoji:'🧸',text:"Your Spotify Wrapped doesn't judge you. It just reflects your emotional journey. All 47 plays of that one song.",sub:'— no judgment'},
{type:'joke',emoji:'🐱',text:"Cats purr to heal their own bones. You're allowed to hum, sing, or make weird noises to feel better too.",sub:'— healing hum'},
{type:'joke',emoji:'🌮',text:"If today was a food, it would be microwave ramen. And you know what? Microwave ramen slaps sometimes.",sub:'— ramen day'},
// ===== AFFIRMATIONS - DIRECT (501-620) =====
{type:'affirm',emoji:'👑',text:"You're worth it. Not because of what you produce. Not because of your job. Because you exist and you're trying.",sub:'— inherently worthy'},
{type:'affirm',emoji:'🌟',text:'You deserve good things. A job that respects you. Rest without guilt. Joy without conditions.',sub:'— you deserve it all'},
{type:'affirm',emoji:'💎',text:'Your worth is not measured in followers, likes, or salary. You are a whole galaxy compressed into a person.',sub:'— immeasurable'},
{type:'affirm',emoji:'🌸',text:"It's okay if today is just about surviving. Tomorrow can be about thriving. One thing at a time.",sub:'— permission granted'},
{type:'affirm',emoji:'🦋',text:"You are allowed to change your mind, your path, your career, your life. Growth isn't betrayal.",sub:'— evolve freely'},
{type:'affirm',emoji:'💫',text:'The stress is temporary. The overwhelm is temporary. But your spirit? Permanent. Unbreakable. Eternal.',sub:'— this too shall pass'},
{type:'affirm',emoji:'🌷',text:"Focus only on the next right thing. Not all the things. Just the one next thing. You can do one thing.",sub:'— one step'},
{type:'affirm',emoji:'🕊️',text:"You don't have to carry burdens that aren't yours. Set them down. Walk lighter.",sub:'— not your weight'},
{type:'affirm',emoji:'🌺',text:'Life is allowed to be simple. Joy is allowed to be quiet. Success is allowed to look different for you.',sub:'— rewrite the rules'},
{type:'affirm',emoji:'✨',text:"Hey. Yes, you. You're doing better than you think. I promise.",sub:'— truth'},
{type:'affirm',emoji:'🐉',text:"You have a dragon's spirit inside you. Patient, ancient, powerful. Let it wake up when you need it.",sub:'— your inner power'},
{type:'affirm',emoji:'🏯',text:"Build your empire quietly. Brick by brick. Nobody needs to see the scaffolding — just the palace you'll become.",sub:'— silent strength'},
{type:'affirm',emoji:'🌊',text:"Like water, you adapt. Like mountains, you endure. Like the moon, you always come back full.",sub:'— elemental'},
{type:'affirm',emoji:'👑',text:"You are not too sensitive. The world is too harsh. Your softness is your rebellion.",sub:'— soft rebellion'},
{type:'affirm',emoji:'🌟',text:"Today I am: breathing, existing, trying. And that is more than enough.",sub:'— today I am'},
{type:'affirm',emoji:'💎',text:"Your boundaries are not walls. They are gates. You decide who gets the key.",sub:'— gatekeeper'},
{type:'affirm',emoji:'🌸',text:"You don't need to prove your pain to deserve help. You don't need to prove your worth to deserve love.",sub:'— no proving'},
{type:'affirm',emoji:'🦋',text:"Asking for less stress isn't asking for too much. That's the bare minimum of a good life.",sub:'— bare minimum'},
{type:'affirm',emoji:'💫',text:"You are not behind schedule. There is no schedule. There is only your life, unfolding.",sub:'— no schedule'},
{type:'affirm',emoji:'🌷',text:"Your needs are not too much. Your feelings are not too much. You are not too much.",sub:'— not too much'},
{type:'affirm',emoji:'🕊️',text:"You don't have to fight every battle. Some things resolve themselves when you stop giving them energy.",sub:'— choose your battles'},
{type:'affirm',emoji:'🌺',text:"It's okay to want a simple, quiet, beautiful life. Not everyone needs to change the world.",sub:'— quiet life'},
{type:'affirm',emoji:'✨',text:"You are allowed to be a work in progress and a masterpiece at the same time.",sub:'— both at once'},
{type:'affirm',emoji:'👑',text:"Your exhaustion is valid. Your overwhelm is valid. Your need for rest is valid. You are valid.",sub:'— valid'},
{type:'affirm',emoji:'🌟',text:"No one is grading your life. There is no score. The only metric that matters is: do you feel okay?",sub:'— no grades'},
{type:'affirm',emoji:'💎',text:"You chose yourself today by opening this app. That tiny act? It's self-love in motion.",sub:'— chose yourself'},
{type:'affirm',emoji:'🌸',text:"The fact that you want a better life means you deserve one. Wanting is not greedy. It's honest.",sub:'— honest wanting'},
{type:'affirm',emoji:'🦋',text:"You are growing even when it doesn't feel like it. Especially when it doesn't feel like it.",sub:'— invisible growth'},
{type:'affirm',emoji:'💫',text:"Whatever you didn't get done today can wait. You cannot. Take care of you first.",sub:'— you first'},
{type:'affirm',emoji:'🌷',text:"Stop apologizing for needing time alone. Solitude is where you remember who you are.",sub:'— solitude'},
{type:'affirm',emoji:'🕊️',text:"You are not defined by your hardest days. You are defined by how gently you return to yourself.",sub:'— gentle return'},
{type:'affirm',emoji:'🌺',text:"Progress looks different every day. Today it might just look like not giving up. That counts.",sub:'— it counts'},
{type:'affirm',emoji:'✨',text:"Your presence in this world is not accidental. You are here on purpose. With purpose.",sub:'— purposeful presence'},
{type:'affirm',emoji:'👑',text:"You are the only you. In all of time. In all the universe. There will never be another. Honor that.",sub:'— only you'},
{type:'affirm',emoji:'🌟',text:"Let go of who you think you should be. Embrace who you actually are. She's wonderful.",sub:'— she's wonderful'},
{type:'affirm',emoji:'💎',text:"Your peace is worth more than their opinion. Always. Always. Always.",sub:'— always peace'},
{type:'affirm',emoji:'🌸',text:"Somewhere right now, someone is thinking of you fondly. You don't even know it. But it's happening.",sub:'— thought of fondly'},
{type:'affirm',emoji:'🦋',text:"You don't have to be fixed because you were never broken. Different isn't damaged.",sub:'— never broken'},
{type:'affirm',emoji:'💫',text:"The version of you that took a chance? She's proud of the version reading this. Keep going.",sub:'— she's proud'},
{type:'affirm',emoji:'🌷',text:"You are allowed to say no without a reason. 'I don't want to' is a complete sentence.",sub:'— no is enough'},
{type:'affirm',emoji:'🕊️',text:"Healing doesn't mean forgetting. It means the memory doesn't control you anymore.",sub:'— free from memory'},
{type:'affirm',emoji:'🌺',text:"Your body carried you through everything. Thank it. Rest it. Feed it something good today.",sub:'— body gratitude'},
{type:'affirm',emoji:'✨',text:"Courage isn't the absence of fear. It's being scared and doing the tiny next thing anyway.",sub:'— tiny courage'},
{type:'affirm',emoji:'👑',text:"You have survived things you never thought you could. That tells you something about what's ahead.",sub:'— survivor strength'},
{type:'affirm',emoji:'🌟',text:"You don't need to earn rest. You don't need to earn love. You don't need to earn being alive.",sub:'— nothing to earn'},
{type:'affirm',emoji:'💎',text:"Today's reminder: you are not your inbox. You are not your to-do list. You are a human. Be one.",sub:'— be human'},
{type:'affirm',emoji:'🌸',text:"Every time you choose kindness toward yourself, you're rewriting the story. Keep rewriting.",sub:'— rewrite'},
{type:'affirm',emoji:'🦋',text:"You don't owe anyone your energy. If something drains you, you're allowed to walk away.",sub:'— walk away'},
{type:'affirm',emoji:'💫',text:"The girl who felt invisible? She's still you. And she deserves to be seen now. See her.",sub:'— see her'},
{type:'affirm',emoji:'🌷',text:"Your feelings are information, not inconvenience. Listen to them. They're trying to help.",sub:'— feelings as info'},
{type:'affirm',emoji:'🕊️',text:"Freedom is knowing you can leave anything that no longer serves you — jobs, habits, people, thoughts.",sub:'— freedom'},
{type:'affirm',emoji:'🌺',text:"You are not too old, too late, or too behind. You are exactly on time for your own life.",sub:'— on time'},
{type:'affirm',emoji:'✨',text:"What you're going through right now is a chapter, not the book. Keep turning the page.",sub:'— just a chapter'},
{type:'affirm',emoji:'👑',text:"You radiate something no one else can. Call it energy, call it spirit, call it you. It's irreplaceable.",sub:'— irreplaceable'},
{type:'affirm',emoji:'🌟',text:"Being gentle with yourself in hard moments isn't weakness. It's the most powerful thing you can do.",sub:'— powerful gentleness'},
{type:'affirm',emoji:'💎',text:"You matter. Not because of what you do or who you know. Just because you're here. That's enough.",sub:'— just because'},
{type:'affirm',emoji:'🌸',text:"Even on days where you accomplish nothing visible, your heart kept beating. Your lungs kept breathing. You stayed.",sub:'— you stayed'},
{type:'affirm',emoji:'🦋',text:"One year from now, you'll wish you started today. But you're also allowed to start tomorrow. Or next week. Or whenever.",sub:'— no pressure'},
{type:'affirm',emoji:'💫',text:"You're allowed to be happy for no reason. You don't need permission. Happiness is your birthright.",sub:'— birthright'},
{type:'affirm',emoji:'🌷',text:"Not everything is a lesson. Sometimes things just happen. It's okay not to find meaning in every pain.",sub:'— sometimes things just happen'},
{type:'affirm',emoji:'🕊️',text:"The world is heavy but you are not required to carry all of it. Put most of it down. Keep only what's yours.",sub:'— only what's yours'},
// ===== MICRO-STORIES (621-750) =====
{type:'vibe',emoji:'📖',text:'She quit her job on a Tuesday. Not dramatically. Just quietly. Packed her desk plant. Walked out into sunshine. The world didn\'t end. It began.',sub:'— new chapter'},
{type:'vibe',emoji:'🌸',text:'There was a woman who planted a garden every time she was sad. By the time she healed, she lived in a forest.',sub:'— garden of healing'},
{type:'vibe',emoji:'🐉',text:'The dragon didn\'t guard gold. It guarded a library. And it let in anyone who came with gentle hands and curious eyes.',sub:'— gentle dragons'},
{type:'vibe',emoji:'🏮',text:'In a city of rushing people, one girl always walked slowly. They called her strange. She called herself present.',sub:'— the slow girl'},
{type:'vibe',emoji:'🌙',text:'The moon wrote letters to the ocean every night. The ocean replied with tides. Some love stories don\'t need words.',sub:'— wordless love'},
{type:'vibe',emoji:'☕',text:'She opened a bookshop at 40. Everyone said it was too late. The books didn\'t know that. They sold themselves to grateful hands.',sub:'— never too late'},
{type:'vibe',emoji:'🦋',text:'A butterfly landed on her shoulder during the worst meeting of her life. She took it as a sign. Quit the next day.',sub:'— butterfly sign'},
{type:'vibe',emoji:'🌊',text:'He drove to the ocean at 3 AM because the apartment walls were too close. The horizon fixed something no therapist could.',sub:'— ocean therapy'},
{type:'vibe',emoji:'🏯',text:'In another life, you are a scholar in a mountain temple. In this one, you\'re still learning. Both are valid paths to wisdom.',sub:'— mountain scholar'},
{type:'vibe',emoji:'📚',text:'The library was enchanted. Every book you touched became the exact story you needed to hear that day.',sub:'— magic library'},
{type:'vibe',emoji:'🌸',text:'She wrote her novel in coffee shops, trains, and waiting rooms. No desk. No routine. Just whenever the words came.',sub:'— words come'},
{type:'vibe',emoji:'🐉',text:'The last dragon didn\'t breathe fire. It breathed warmth. People came from miles to sit near it on cold nights.',sub:'— warmth dragon'},
{type:'vibe',emoji:'🏮',text:'The old woman said: "The secret to a good life is very simple. Hot tea, good stories, and at least one person who really sees you."',sub:'— the secret'},
{type:'vibe',emoji:'🌙',text:'Every night, she collected moonlight in jars. Not for herself. For anyone who needed a little light in the morning.',sub:'— moonlight jars'},
{type:'vibe',emoji:'☕',text:'The café existed between worlds. You could only find it when you really needed it. Today, you found it.',sub:'— between worlds'},
{type:'vibe',emoji:'🦋',text:'She didn\'t become a butterfly overnight. First she was soup. Actual soup. And that was the bravest part.',sub:'— brave soup'},
{type:'vibe',emoji:'🌊',text:'The sailor asked the sea for direction. The sea said: "I don\'t give directions. I give freedom." He never went home.',sub:'— sea freedom'},
{type:'vibe',emoji:'🏯',text:'A thousand paper cranes hung from her ceiling. Not for a wish. For patience. Each one taught her to wait beautifully.',sub:'— beautiful waiting'},
{type:'vibe',emoji:'📚',text:'She found a note in a secondhand book: "If you\'re reading this, you needed this book. Trust that." She did.',sub:'— trust the book'},
{type:'vibe',emoji:'🌸',text:'In the quiet after the storm, a single cherry tree bloomed. It hadn\'t been there yesterday. Some things grow fast when they\'re ready.',sub:'— sudden bloom'},
{type:'vibe',emoji:'🐉',text:'The girl who was afraid of everything adopted a baby dragon. They taught each other courage.',sub:'— mutual courage'},
{type:'vibe',emoji:'🏮',text:'He wrote his feelings on lanterns and released them into the sky. By morning, he was lighter. The sky carried the rest.',sub:'— sky letters'},
{type:'vibe',emoji:'🌙',text:'The old bookshop closed at midnight. But if you knocked three times after, the owner would let you in for tea and stories.',sub:'— midnight stories'},
{type:'vibe',emoji:'☕',text:'She started a café with only window seats. "People deserve views while they think," she said.',sub:'— window seat café'},
{type:'vibe',emoji:'🦋',text:'He planted wildflowers on his balcony. The butterflies came first. Then the hummingbirds. Then the peace.',sub:'— balcony peace'},
{type:'vibe',emoji:'🌊',text:'She kept a jar of sea glass. Each piece was a hard day smoothed by time. The jar was almost full. She was almost healed.',sub:'— sea glass jar'},
{type:'vibe',emoji:'🏯',text:'The temple bell rang at 4 AM. Not as an alarm. As an invitation. "Come sit with us," it said. "Bring nothing but breath."',sub:'— morning invitation'},
{type:'vibe',emoji:'📚',text:'She read a book a week for a year. By December, she was a different person. The books didn\'t change. She did.',sub:'— reading changed her'},
{type:'vibe',emoji:'🌸',text:'He left a sticky note on the bathroom mirror every morning: "You again? Lucky world." It became his religion.',sub:'— lucky world'},
{type:'vibe',emoji:'🐉',text:'In the kingdom of rushing, there lived a queen who napped without apology. Her subjects flourished under her well-rested rule.',sub:'— nap queen'},
{type:'vibe',emoji:'🏮',text:'The night market vendor sold nothing but compliments. "Your eyes carry stories," she\'d say. People left richer than before.',sub:'— compliment vendor'},
{type:'vibe',emoji:'🌙',text:'She whispered her dreams to the moon every night. Not because the moon could grant them. But because saying them made them real.',sub:'— speaking dreams'},
{type:'vibe',emoji:'☕',text:'They met in a bookshop. Reached for the same book. Laughed. Some stories begin exactly like stories should.',sub:'— bookshop meeting'},
{type:'vibe',emoji:'🦋',text:'The girl collected words like stones. Kept them in her pockets. On hard days, she\'d reach in and find exactly the right one.',sub:'— pocket words'},
{type:'vibe',emoji:'🌊',text:'A sailor retired at 35. Bought a cottage by the sea. Wrote poetry no one read. Was the happiest he\'d ever been.',sub:'— cottage poet'},
{type:'vibe',emoji:'🏯',text:'The mountain sage had one rule: "If it will not matter in five years, do not give it more than five minutes today."',sub:'— sage rule'},
{type:'vibe',emoji:'📚',text:'She wrote four novels in her head before writing one on paper. All five versions were beautiful. The imagined ones most of all.',sub:'— imagined novels'},
{type:'vibe',emoji:'🌸',text:'The cherry tree bloomed every spring. It never questioned whether it deserved to. It just did. Take notes.',sub:'— just bloom'},
{type:'vibe',emoji:'🐉',text:'The dragon and the girl made a deal: she\'d keep its secret (it was shy), and it would fly her anywhere when she felt trapped.',sub:'— escape dragon'},
{type:'vibe',emoji:'🏮',text:'In the city of lost things, there was a shop that sold found dreams. She bought back her own for three gold coins.',sub:'— buying back dreams'},
{type:'vibe',emoji:'🌙',text:'Every time she said "I can\'t," the universe said "not yet." There\'s a difference. A vast, hopeful difference.',sub:'— not yet'},
{type:'vibe',emoji:'☕',text:'The barista drew a flower in her latte. Nobody asked him to. Some kindness is just art that happens.',sub:'— latte flower'},
{type:'vibe',emoji:'🦋',text:'She kept a list of things that went right. Not a gratitude journal — a proof-of-life journal. Evidence that good exists.',sub:'— proof of life'},
{type:'vibe',emoji:'🌊',text:'The lighthouse keeper never needed saving. She needed company. Sometimes strength is lonely.',sub:'— lonely strength'},
{type:'vibe',emoji:'🏯',text:'A poet wrote one good line a day. In ten years, she had 3,650 good lines. Enough for several lifetimes of beauty.',sub:'— one line a day'},
{type:'vibe',emoji:'📚',text:'The bookmark fell out and she lost her page. Started from the beginning. Found details she\'d missed. Maybe losing your place isn\'t always bad.',sub:'— lost your page'},
{type:'vibe',emoji:'🌸',text:'She danced alone in her kitchen at 2 PM on a Wednesday. The neighbors couldn\'t see. The joy didn\'t need witnesses.',sub:'— kitchen dance'},
{type:'vibe',emoji:'🐉',text:'The smallest dragon in the kingdom couldn\'t fly. So it learned to make the best tea. Sometimes your gift isn\'t what you expected.',sub:'— unexpected gift'},
{type:'vibe',emoji:'🏮',text:'He put fairy lights in his apartment. Not for anyone else. For himself. Because his own eyes deserved something beautiful.',sub:'— fairy lights for one'},
{type:'vibe',emoji:'🌙',text:'She stopped waiting for the right time and started calling this time good enough. It was. It always had been.',sub:'— good enough time'},
// ===== MORE QUOTES - SEASONAL & COZY (751-870) =====
{type:'quote',emoji:'🍂',text:"Autumn teaches us that letting go can be beautiful. Drop what's heavy. Watch it become gold.",sub:'— autumn wisdom'},
{type:'quote',emoji:'🌧️',text:"Rainy days exist so cozy days have meaning. Embrace the contrast.",sub:'— rainy purpose'},
{type:'quote',emoji:'☃️',text:"Winter is just the world resting. You're allowed to rest too. Hibernate if you need to.",sub:'— winter rest'},
{type:'quote',emoji:'🌱',text:"Spring doesn't rush. It arrives exactly when the ground is ready. So will your next chapter.",sub:'— spring timing'},
{type:'quote',emoji:'🍂',text:"Sweater weather is nature's permission slip to slow down. Take it.",sub:'— slow down season'},
{type:'quote',emoji:'🌧️',text:"The sound of rain is the earth processing its feelings. You can process yours too.",sub:'— rain feelings'},
{type:'quote',emoji:'☃️',text:"Cold weather means hot drinks, warm blankets, and zero obligations to be outside. Cocoon yourself.",sub:'— cocoon season'},
{type:'quote',emoji:'🌱',text:"Every flower was once underground in total darkness. And it still became itself.",sub:'— darkness to bloom'},
{type:'quote',emoji:'🍂',text:"Golden hour lasts all day in autumn. Some seasons are just inherently kinder to your soul.",sub:'— golden season'},
{type:'quote',emoji:'🌧️',text:"Let it rain. Let it wash. Let it clean. Not everything needs to be sunny to be good.",sub:'— let it rain'},
{type:'quote',emoji:'🌸',text:"Spring cleaning isn't just for closets. Clean out the beliefs that no longer serve you.",sub:'— spring clean your mind'},
{type:'quote',emoji:'☀️',text:"Summer exists to remind you that warmth is your natural state. Even when life feels cold.",sub:'— warmth is home'},
{type:'quote',emoji:'🍂',text:"Trees don't fight losing their leaves. They just trust they'll grow new ones. Trust your cycles.",sub:'— trust cycles'},
{type:'quote',emoji:'🌧️',text:"Gray skies aren't sad skies. They're soft skies. Gentle skies. Permission-to-be-quiet skies.",sub:'— gray permission'},
{type:'quote',emoji:'🌱',text:"New beginnings don't always feel new. Sometimes they feel terrifying. That's still beginning.",sub:'— terrifying beginnings'},
{type:'quote',emoji:'☃️',text:"Blanket burrito. Hot cocoa. No plans. Sometimes that IS the plan. And it's a perfect plan.",sub:'— burrito plan'},
{type:'quote',emoji:'🍂',text:"Some days have the energy of a Sunday morning. Claim that energy even on a Wednesday.",sub:'— sunday energy'},
{type:'quote',emoji:'🌧️',text:"Petrichor: the smell of rain on dry earth. Even language celebrates the beauty of storms ending.",sub:'— petrichor'},
{type:'quote',emoji:'🌸',text:"Cherry blossoms last two weeks. That's what makes them precious. Your hard times are temporary too.",sub:'— temporary beauty'},
{type:'quote',emoji:'☀️',text:"Sunlight doesn't knock. It just shows up. Let good things find you without an invitation.",sub:'— uninvited good'},
{type:'quote',emoji:'🍂',text:"Cozy isn't a season. It's a decision. Wrap yourself in it today.",sub:'— choose cozy'},
{type:'quote',emoji:'🌧️',text:"Some of your best ideas will come on rainy afternoons when you're supposed to be doing nothing.",sub:'— rainy ideas'},
{type:'quote',emoji:'🌱',text:"You are perennial. You come back. Every time. Stronger, softer, wiser.",sub:'— perennial'},
{type:'quote',emoji:'☃️',text:"The world gets quiet under snow. Give yourself that same quiet. Muffle the noise.",sub:'— snow quiet'},
{type:'quote',emoji:'🌸',text:"If cherry blossoms can be breathtaking in their impermanence, so can this moment.",sub:'— breathtaking now'},
{type:'quote',emoji:'☀️',text:"Warm sun on closed eyelids. That feeling? You can carry it inside you. Access it anytime.",sub:'— internal sun'},
{type:'quote',emoji:'🍂',text:"The world doesn't stop being beautiful just because you're sad. Let beauty coexist with pain.",sub:'— coexistence'},
{type:'quote',emoji:'🌧️',text:"Dancing in the rain isn't about ignoring the storm. It's about choosing joy inside it.",sub:'— dance anyway'},
{type:'quote',emoji:'🌱',text:"Seeds don't know what they're becoming. They just grow toward light. Follow the light. Any light.",sub:'— follow the light'},
{type:'quote',emoji:'🌙',text:"Moonlit walks solve more problems than midnight overthinking ever could. Step outside.",sub:'— moonlit solution'},
{type:'quote',emoji:'🌸',text:"First day of spring energy: everything is possible, nothing is due, life is just beginning.",sub:'— spring energy'},
{type:'quote',emoji:'☀️',text:"Summer evenings where time slows to honey. Carry that slowness with you into busy seasons.",sub:'— honey time'},
{type:'quote',emoji:'🍂',text:"The trees don't apologize for being bare in winter. You don't have to apologize for your empty seasons.",sub:'— bare seasons'},
{type:'quote',emoji:'🌧️',text:"Storm clouds are just the sky being dramatic. Let yourself be dramatic sometimes too. Then let it pass.",sub:'— sky drama'},
{type:'quote',emoji:'🌱',text:"Every garden was once just dirt and hope. You have both. That's enough to start.",sub:'— dirt and hope'},
{type:'quote',emoji:'🌙',text:"Night is not the absence of day. It's its own kind of presence. Honor your dark hours.",sub:'— night presence'},
{type:'quote',emoji:'🌸',text:"Floral abundance exists to show you: the universe doesn't believe in scarcity. Neither should you.",sub:'— no scarcity'},
{type:'quote',emoji:'☀️',text:"Sunrise is proof that no matter how dark the night, light comes back. It always comes back.",sub:'— light returns'},
{type:'quote',emoji:'🍂',text:"A cup of something warm in both hands. Nowhere to be. Watching the world through a window. That's wealth.",sub:'— real wealth'},
{type:'quote',emoji:'🌧️',text:"Let today be gentle. Whatever happens, let it happen gently.",sub:'— gentle today'},
{type:'quote',emoji:'🌱',text:"You planted seeds in the dark. One day you'll wake up in a garden. Keep watering.",sub:'— keep watering'},
{type:'quote',emoji:'🌙',text:"Full moons are for releasing. New moons are for planting. Where are you in your cycle?",sub:'— moon cycle'},
{type:'quote',emoji:'🌸',text:"Bloom where you're planted. But also: you're allowed to transplant yourself somewhere better.",sub:'— transplant'},
{type:'quote',emoji:'☀️',text:"Some days the sun comes out and your only job is to stand in it. Today might be that day.",sub:'— stand in the sun'},
{type:'quote',emoji:'🍂',text:"Hot coffee. Cool air. Changing leaves. Soft sweater. Some happiness requires no explanation.",sub:'— simple happy'},
{type:'quote',emoji:'🌧️',text:"After heavy rain, the air is cleanest. After hard times, your clarity is sharpest.",sub:'— post-rain clarity'},
{type:'quote',emoji:'🌱',text:"Nature never says 'I'll bloom when I'm ready but only if conditions are perfect.' It just blooms. You can too.",sub:'— bloom imperfectly'},
{type:'quote',emoji:'🌙',text:"The night sky doesn't compete with the day. It just waits its turn and shows up differently beautiful.",sub:'— differently beautiful'},
{type:'quote',emoji:'🌸',text:"Every petal that falls is making room for the fruit. Every ending you survive is making room for something nourishing.",sub:'— room for fruit'},
// ===== MORE QUOTES - ANTI-HUSTLE & BOUNDARIES (871-1000) =====
{type:'quote',emoji:'🛌',text:"Rest is not a reward for productivity. It's a requirement for being human. Take it.",sub:'— take rest'},
{type:'quote',emoji:'🚫',text:"'No' is a complete sentence. You don't need to explain, justify, or apologize for protecting your energy.",sub:'— just no'},
{type:'quote',emoji:'🧘',text:"Hustle culture is a scam. The richest people in the world have hobbies. You're allowed to just live.",sub:'— anti-hustle'},
{type:'quote',emoji:'🌙',text:"Sleep is not lazy. Naps are not failure. Rest is how your brain processes everything you've been through.",sub:'— sleep is work'},
{type:'quote',emoji:'🕊️',text:"Not every opportunity is yours to take. Some doors are for other people. Your door has your name on it.",sub:'— your door'},
{type:'quote',emoji:'🌸',text:"You are not a machine. Machines don't need sunsets and warm baths and silly songs. But you do. Honor that.",sub:'— not a machine'},
{type:'quote',emoji:'💫',text:"Doing less isn't failing. Sometimes doing less is the most radical act of self-preservation.",sub:'— radical rest'},
{type:'quote',emoji:'🌿',text:"Your worth doesn't decrease when your productivity does. They were never connected in the first place.",sub:'— disconnected worth'},
{type:'quote',emoji:'🛌',text:"Cancel the plan. Turn off the phone. Draw the curtains. Some days are for disappearing and that's okay.",sub:'— disappear days'},
{type:'quote',emoji:'🚫',text:"You don't have to respond to that text today. Or tomorrow. Or ever. Your attention is yours to give.",sub:'— your attention'},
{type:'quote',emoji:'🧘',text:"Meditation isn't about emptying your mind. It's about not following every thought off a cliff.",sub:'— thought ledge'},
{type:'quote',emoji:'🌙',text:"8 PM is a perfectly acceptable bedtime for an adult. Fight me.",sub:'— 8 PM bedtime'},
{type:'quote',emoji:'🕊️',text:"Some relationships are seasons, not lifetimes. Let the autumn ones go with grace.",sub:'— seasonal people'},
{type:'quote',emoji:'🌸',text:"You're allowed to outgrow people without it being anyone's fault. Sometimes paths just diverge.",sub:'— diverging paths'},
{type:'quote',emoji:'💫',text:"The pressure you feel isn't from the universe. It's from a system designed to extract. Opt out where you can.",sub:'— opt out'},
{type:'quote',emoji:'🌿',text:"Guilt is not a good reason to do anything. If guilt is the only motivator, let the thing go.",sub:'— guilt is not a reason'},
{type:'quote',emoji:'🛌',text:"The best thing you can do for everyone around you is take care of yourself first. Oxygen mask rule.",sub:'— oxygen mask'},
{type:'quote',emoji:'🚫',text:"Unfollow. Mute. Block. Curate your digital world like your mental health depends on it. Because it does.",sub:'— curate ruthlessly'},
{type:'quote',emoji:'🧘',text:"Busyness is not a badge of honor. Calm is. Peace is. Having time is.",sub:'— calm badge'},
{type:'quote',emoji:'🌙',text:"You know what's productive? A walk with no destination. A thought with no outcome. A moment with no purpose.",sub:'— purposeless moments'},
{type:'quote',emoji:'🕊️',text:"Let people be wrong about you. Their understanding of you is not your responsibility.",sub:'— let them be wrong'},
{type:'quote',emoji:'🌸',text:"A slow morning is a radical act. Protect it. The world can wait 30 more minutes.",sub:'— slow morning'},
{type:'quote',emoji:'💫',text:"You were not born to pay bills and die. You were born to create, love, wonder, and rest. Do those today.",sub:'— what you were born for'},
{type:'quote',emoji:'🌿',text:"If your body says stop, stop. It's not being dramatic. It's saving you from yourself.",sub:'— body says stop'},
{type:'quote',emoji:'🛌',text:"Burnout isn't a badge of dedication. It's a signal you've been giving more than you have. Refill.",sub:'— refill yourself'},
{type:'quote',emoji:'🚫',text:"Stop romanticizing being busy. Start romanticizing having free time, good sleep, and inner peace.",sub:'— romanticize rest'},
{type:'quote',emoji:'🧘',text:"Answering emails at 11 PM isn't dedication. It's a boundary problem. Set the boundary.",sub:'— 11 PM boundary'},
{type:'quote',emoji:'🌙',text:"The moon doesn't hustle. It just shows up in its own time, in its own phase. Moon energy.",sub:'— moon energy'},
{type:'quote',emoji:'🕊️',text:"Protect your Saturdays like they're sacred. Because they are.",sub:'— sacred Saturdays'},
{type:'quote',emoji:'🌸',text:"You don't have to 'make the most' of every single moment. Some moments are just for being in.",sub:'— just be in it'},
{type:'quote',emoji:'💫',text:"If rest feels unproductive, that's conditioning. Not truth. The truth is: rest is how you last.",sub:'— rest is how you last'},
{type:'quote',emoji:'🌿',text:"A garden doesn't grow faster because you shout at it. Neither do you. Be patient with yourself.",sub:'— patient growth'},
{type:'quote',emoji:'🛌',text:"The world glorifies the grind. But the grind doesn't care about you. Take care of yourself instead.",sub:'— the grind doesn\'t care'},
{type:'quote',emoji:'🚫',text:"Toxic positivity says 'be grateful.' Real wisdom says 'feel what you feel. Then, if you want, find the lesson.'",sub:'— feel first'},
{type:'quote',emoji:'🧘',text:"Your energy is a resource. Spend it like money. Save some. Invest wisely. Don't give it all away.",sub:'— energy budget'},
{type:'quote',emoji:'🌙',text:"It's 3 PM. You're tired. That's not a flaw. That's biology. Rest.",sub:'— 3 PM slump'},
{type:'quote',emoji:'🕊️',text:"You don't have to have an opinion on everything. You don't have to engage with every debate. Peace is opting out.",sub:'— opt out of noise'},
{type:'quote',emoji:'🌸',text:"Your life doesn't need to be Instagram-worthy. It needs to be livable. And enjoyable. For you.",sub:'— livable life'},
{type:'quote',emoji:'💫',text:"Not all growth requires pain. Some growth happens in sunshine, in laughter, in ease. Seek that growth too.",sub:'— ease growth'},
{type:'quote',emoji:'🌿',text:"Delete the app. Skip the event. Ignore the news cycle. Your peace is not selfish — it's survival.",sub:'— peace is survival'},
{type:'quote',emoji:'🛌',text:"Imagine being well-rested. Imagine having free time. Now: protect those things like your life depends on it.",sub:'— protect your rest'},
{type:'quote',emoji:'🚫',text:"You don't have to explain your No. You don't have to soften your No. No is already gentle enough.",sub:'— no is gentle'},
{type:'quote',emoji:'🧘',text:"Some days the most productive thing is to close the laptop and look out the window for 10 minutes.",sub:'— window minutes'},
{type:'quote',emoji:'🌙',text:"Be the person who goes to bed on time. Revolutionary. Countercultural. Well-rested.",sub:'— bedtime rebel'},
{type:'quote',emoji:'🕊️',text:"You're not lazy for wanting a calm life. Ambition doesn't have to be loud. Quiet ambition counts.",sub:'— quiet ambition'},
{type:'quote',emoji:'🌸',text:"The world doesn't need you to be productive today. It needs you to be gentle with yourself today.",sub:'— gentle today'},
{type:'quote',emoji:'💫',text:"If you're reading this between 1 and 5 PM, this is your sign to take a break. Stand up. Stretch. Breathe.",sub:'— afternoon sign'},
{type:'quote',emoji:'🌿',text:"You don't need to be doing more. You might actually need to be doing less. Much less. Start there.",sub:'— do less'},
{type:'quote',emoji:'🛌',text:"Nap without guilt. Rest without earning it. Exist without producing. You are more than output.",sub:'— more than output'},
{type:'quote',emoji:'🚫',text:"Not my circus. Not my monkeys. Not my problem to solve. — A mantra for every afternoon.",sub:'— not my circus'},
{type:'quote',emoji:'🧘',text:"Ten minutes of doing nothing is not wasted time. It's recalibration. It's necessary. It's medicine.",sub:'— nothing medicine'},
{type:'quote',emoji:'🌙',text:"The stars don't hustle. They just burn steadily for billions of years. That's sustainable energy. Be that.",sub:'— steady star'},
{type:'quote',emoji:'🕊️',text:"Choose yourself as often as you choose others. Actually, choose yourself more. You've been last too long.",sub:'— choose yourself first'},
{type:'quote',emoji:'🌸',text:"This is your daily reminder that you don't have to earn the right to exist peacefully. It's already yours.",sub:'— already yours'},
{type:'quote',emoji:'💫',text:"The afternoon slump is real. You're not failing. You're human. This app exists because 1-5 PM is hard. I see you.",sub:'— I see you'},
{type:'quote',emoji:'🌿',text:"Doing nothing productive today doesn't erase what you built yesterday. Progress is cumulative. Rest is part of it.",sub:'— cumulative'},
{type:'quote',emoji:'🛌',text:"You have permission to not finish that today. Or tomorrow. Or this week. Done is not the only option. Rest is too.",sub:'— permission to pause'},
{type:'quote',emoji:'🚫',text:"Stop performing wellness. Actually rest. Actually say no. Actually do nothing. The real thing, not the aesthetic.",sub:'— real rest'},
{type:'quote',emoji:'🧘',text:"If your to-do list makes you anxious, cross three things off without doing them. Watch the world not end.",sub:'— cross them off'},
{type:'quote',emoji:'🌙',text:"You've done enough today. Even if 'enough' is just getting through. That's a full day's work sometimes.",sub:'— full day\'s work'},
{type:'quote',emoji:'🕊️',text:"Be wildly unproductive this evening. On purpose. With joy. Call it self-care. Call it rebellion. Call it Tuesday.",sub:'— unproductive joy'},
{type:'quote',emoji:'🌸',text:"You made it to this moment. Every moment before this, you survived. Your track record is flawless.",sub:'— flawless record'},
{type:'quote',emoji:'💫',text:"Close this app when you're ready. Take what you needed. Leave the rest. Come back whenever. I'll be here.",sub:'— I\'ll be here'},
];
